# Generated by Django 2.2.2 on 2019-06-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='desciption',
            new_name='description',
        ),
    ]
