# Generated by Django 2.2.2 on 2019-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_view', '0002_auto_20190622_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='作品标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='默认的描述', max_length=100),
        ),
    ]
